### PR TITLE
Replace tcell with roll-our-own

### LINKED ISSUE #34: Avoid screen refreshes
Using this: <https://github.com/gdamore/tcell/issues/422>

I did some profiling, and my terminal app is maxing out the CPU while I'm scrolling.

If I could *not* update the screen when there are pending events, that would improve things. I have experimented and it was nice!

Ref: <https://github.com/walles/moar/blob/db4acb57ef8b455ab3293e1b7e9e7c27d8688e97/m/pager.go#L781-L782>

### LINKED ISSUE #37: Fix shutdown hang
# Try this
* Open `moar` on a large file
* Mouse scroll a lot
* Press `q` while the mouse scroll is catching up (#34)

# Current result
`moar` closes its display, but then hangs without giving any prompt back. Ctrl-C doesn't help, it has to be killed.

# Expected result
A clean exit.

### PR DESCRIPTION
**Pull request by walles**
* Fixes #37
* Fixes #34
* Makes window resizing smoother.

Before this change, the main loop was roughly:
* Await one single user input event
* Handle single user input event
* Redraw screen

With this change in place, the main loop is:
* Await one single user input event (like before)
* Handle single user input event (like before)
* If there are no more events, redraw screen (new!)

The difference is huge if you do a fling scroll on a trackpad. Before, scrolling was slow at constant speed, and the scrolling kept on at that slow constant speed way longer than what it should have. Now, scrolling feels just like it should.

### CODE REVIEW

**Comment by walles** [comment]
@89z could you test this on Windows?

You provided Windows screenshots in #33 so I assume you have a Windows machine with a Go environment set up.

**Comment by 89z** [comment]
> If you could just build `moar` from this branch and try using it to view some
> file that would be swell!

What branch?

Also, regarding performance, I noticed that this commit in another reposistory nearly doubled scroll speed (in a good way):

https://github.com/noborus/ov/commit/affc040e

I dont know if it helps, since its a different codebase, but might be worth looking at.

**Comment by walles** [comment]
@89z thanks!

I excluded SIGWINCH handling on Windows, if you could make another try that would be awesome!

**Comment by walles** [comment]
Build + unit testing now pass on Windows, I added a Travis config so any breakage should become obvious.

Could still be visually all-broken though, needs testing on an actual Windows machine.

Just starting `moar` on some file and verifying...
* Scroll down
* Quit

... should cover most Windows specific cases.

**Comment by 89z** [comment]
Nope, doesnt work at all. I get this:

~~~
panic: read /dev/stdout: The handle is invalid.
~~~

You realize `/dev/stdout` doesnt exist on Windows right?

**Comment by walles** [comment]
I think it's because of this, no explicit access to `/dev/stdout` (which is actually Linux specific, and I'm on macOS) is ever done:

https://github.com/walles/moar/blob/7cd157174c028049ffa87c4b230a578c67a5481b/twin/screen.go#L105-L114

I'll see if I can figure out some way of testing this on Windows somehow.

**Comment by 89z** [comment]
If you are trying to roll your own `/dev/tty`, you will need to use this for Windows [1]:

~~~go
out, err := syscall.Open("CONOUT$", syscall.O_RDWR, 0)
~~~

or call a module [2].

1. https://github.com/mattn/go-tty/blob/72ed86c4/tty_windows.go#L163
2. https://pkg.go.dev/github.com/mattn/go-tty

**Comment by walles** [comment]
Found a Windows machine, will fix things up there.

**Pull request closed without merging**
